a = int(input("Enter any number: "))
b = int(input("Enter any number: "))
print ("The ans of",a,"+",b,"=",a+b)
print ("The ans of",a,"-",b,"=",a-b)
print ("The ans of",a,"*",b,"=",a*b)
print ("The ans of",a,"/",b,"=",a/b)
print ("The ans of",a,"%",b,"=",a%b)